#!/bin/bash

whereami=$(cd `dirname "$0"`; pwd -P)
myname=`basename "$0"`
dir="$1"
lib_dir="$2/$myname"
build_info="$3"

mkdir -p $lib_dir

(cd $dir && \
  (make distclean || true) && \
  cp $build_info crypto/sha/build.info && \
  ./Configure --prefix=$lib_dir linux-x86_64 && \
  make && \
  make install_runtime_libs && \
  git checkout crypto/sha/build.info
)
