# -*- Makefile -*-

# --------------------------------------------------------------------
-include ../../../Makefile.common

# --------------------------------------------------------------------
.PHONY: default clean

default: shake256.japp shake256.s
	@true

clean:
	rm -f shake256.japp shake256.s
