#!/bin/bash

version=`cat config/version`
bench=`cat config/work`

if [ "$#" -eq 1 ]; then
 bench=$1
fi

cat config/$bench | egrep -v "^$|^#" | while read implementation
do
 implementation_expand=`eval echo -n $implementation`
 implementation_cut=`echo -n $implementation | cut -d' ' -f1-3`
 (cd supercop-$version && (./do-part $implementation_expand || true))
 implementationid=`echo "$implementation_cut" | sed -e 's/\//_/g' -e 's/\ /_/g'`.data
 find supercop-$version/bench/ -name data -exec cp {} data/$implementationid \;
done
