#!/bin/bash

# remove previous benchmarks files related to chacha20
ls data/crypto_stream_chacha20_* | xargs rm

# copy implementations and bindings into supercop-*
./sync
./sync openssl
./sync libsodium
./sync hacl-star

# run benchmarks... this should take some time
./bench chacha20

# move openssl static results to openssl static avx2
mv data/crypto_stream_chacha20_openssl_static.data data/crypto_stream_chacha20_openssl_static_avx2.data

# disable avx2 and run openssl benchmarks
(export OPENSSL_ia32cap=~0x200000200000000 && ./bench chacha20-openssl && unset OPENSSL_ia32cap)
mv data/crypto_stream_chacha20_openssl_static.data data/crypto_stream_chacha20_openssl_static_avx.data

# plot
./plot chacha20 xor_cycles 16 512
./plot chacha20 xor_cycles 512 4096
./plot chacha20 xor_cycles 4096 16384
