#!/bin/bash

# remove previous benchmarks files related to chacha20
ls data/crypto_stream_chacha20_* | xargs rm

# copy implementations and bindings into supercop-*
./sync
./sync openssl
./sync libsodium
./sync hacl_star

## run benchmarks... this should take some time
./bench chacha20

# move openssl static results to openssl static avx2
mv data/crypto_stream_chacha20_openssl_static.data data/crypto_stream_chacha20_openssl_static_avx2.data

# disable avx2 and run openssl benchmarks
(export OPENSSL_ia32cap=~0x200000200000000 && ./bench chacha20-openssl && unset OPENSSL_ia32cap)
mv data/crypto_stream_chacha20_openssl_static.data data/crypto_stream_chacha20_openssl_static_avx.data

# plot
./plot chacha20 xor_cycles 16 512 "(jazz|openssl)"
./plot chacha20 xor_cycles 512 4096 "(jazz|openssl)"
./plot chacha20 xor_cycles 4096 16384 "(jazz|openssl)"

./plot chacha20 xor_cycles 16 512 "(jazz|hacl_star_gcc)"
./plot chacha20 xor_cycles 512 4096 "(jazz|hacl_star_gcc)"
./plot chacha20 xor_cycles 4096 16384 "(jazz|hacl_star_gcc)"

./plot chacha20 xor_cycles 16 512 "(jazz|hacl_star_compcert)"
./plot chacha20 xor_cycles 512 4096 "(jazz|hacl_star_compcert)"
./plot chacha20 xor_cycles 4096 16384 "(jazz|hacl_star_compcert)"

./plot chacha20 xor_cycles 16 512 "(jazz|libsodium)"
./plot chacha20 xor_cycles 512 4096 "(jazz|libsodium)"
./plot chacha20 xor_cycles 4096 16384 "(jazz|libsodium)"

./plot chacha20 xor_cycles 16 512
./plot chacha20 xor_cycles 512 4096
./plot chacha20 xor_cycles 4096 16384

today=`date "+%Y%m%d"`
mkdir -p data/chacha20-$today

ls data/*chacha20*.* | egrep -v "\.data$" | while read file
do
  mv $file data/chacha20-$today
done
