#!/bin/bash

# remove previous benchmarks files related to keccak
ls data/crypto_hash_shake* | xargs rm

# copy implementations and bindings into supercop-*
./sync

prev_ld_library_path=`echo -n $LD_LIBRARY_PATH`

## run benchmarks with openssl compiled with default keccak
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/third_party_shared_libs/openssl/lib/
sudo ldconfig
./bench keccak
mv data/crypto_hash_shake256_openssl.data data/crypto_hash_shake256_openssl_ref.data
mv data/crypto_hash_shake128_openssl.data data/crypto_hash_shake128_openssl_ref.data

## run with keccak avx2
export LD_LIBRARY_PATH=$prev_ld_library_path:`pwd`/third_party_shared_libs/openssl-keccak-avx2/lib/
sudo ldconfig
echo $LD_LIBRARY_PATH
./bench keccak-openssl-avx2
mv data/crypto_hash_shake256_openssl.data data/crypto_hash_shake256_openssl_avx2.data
mv data/crypto_hash_shake128_openssl.data data/crypto_hash_shake128_openssl_avx2.data

./plot shake128 cycles 128 16384 ""
./plot shake256 cycles 128 16384 ""

exit

