#!/bin/bash

ILIST="sha3224 sha3256 sha3384 sha3512 shake128 shake256"

# remove previous benchmarks files related to keccak
rm -f data/crypto_hash_sha3*
rm -f data/crypto_hash_shake*

# copy implementations and bindings into supercop-*
./sync

PREVIOUS_LD_LIBRARY_PATH=`echo -n $LD_LIBRARY_PATH`

### run libjc
./bench keccak

## run benchmarks with openssl configured with no-asm
export LD_LIBRARY_PATH=$PREVIOUS_LD_LIBRARY_PATH:`pwd`/third_party_shared_libs/openssl-no-asm/lib/
sudo ldconfig
./bench keccak-openssl-no-asm
for i in $ILIST; do mv data/crypto_hash_${i}_openssl.data data/crypto_hash_${i}_openssl_no_asm.data; done

## run benchmarks with openssl compiled with default keccak
export LD_LIBRARY_PATH=$PREVIOUS_LD_LIBRARY_PATH:`pwd`/third_party_shared_libs/openssl/lib/
sudo ldconfig
./bench keccak-openssl
for i in $ILIST; do mv data/crypto_hash_${i}_openssl.data data/crypto_hash_${i}_openssl_scalar.data; done

## run with keccak avx2
export LD_LIBRARY_PATH=$PREVIOUS_LD_LIBRARY_PATH:`pwd`/third_party_shared_libs/openssl-keccak-avx2/lib/
sudo ldconfig
echo $LD_LIBRARY_PATH
./bench keccak-openssl-avx2
for i in $ILIST; do mv data/crypto_hash_${i}_openssl.data data/crypto_hash_${i}_openssl_avx2.data; done

## gen plots
for i in $ILIST; do ./plot $i cycles 128 16384 ""; done

today=`date "+%Y%m%d"`
mkdir -p data/keccak-$today

for i in $ILIST
do
  ls data/*$i*.* | egrep -v "\.data$" | while read file
  do
    mv $file data/keccak-$today
  done
done

