#!/bin/bash

if [ "$#" -eq 0 ]; then
 echo "usage: ./plot (chacha20|poly1305) (cycles|xor_cycles) 16 128 (jazz|hacl)"
 exit
fi

operation="$1"
type="$2"
low="$3"
high="$4"
filter="$5"

gnu=data/$1_$2_$5_$3_$4.gnu
png=data/$1_$2_$5_$3_$4.svg

idx=0

echo "set term svg enhanced background rgb 'white'" > $gnu

echo "set logscale x 2" >> $gnu

echo "set output \"$png\"" >> $gnu

for file in $( ls data/*${operation}*.data | egrep "${filter}" )
do
 egrep -o " $type [0-9]+ [0-9]+" "$file" |
 awk -v low=$low -vhigh=$high '{if($2 >= low && $2 <= high){printf("%d, %.2f\n", $2,($3/$2))}}' |
 sort -t, -g -k1 -k2 | sort -t, -g -k1,1 -u  > "${file%.data}_$low_$high.csv"
 list[$idx]="${file%.data}_$low_$high.csv";
 idx=$((idx+1))
done


if [ $idx -gt 0 ]; then
 echo -n "plot " >> $gnu
 while [ $idx -gt 1 ]
 do
  idx=$((idx-1))
  title=${list[$idx]//_/\\_}
  echo "\"${list[$idx]}\" using 1:2 title '$title' with lines, \\"  >> $gnu
 done
 title=${list[0]//_/\\_}
 echo "\"${list[0]}\" using 1:2 title '$title' with lines"  >> $gnu
fi

echo "unset logscale x" >> $gnu

gnuplot $gnu

