#!/bin/bash

if [ "$#" -eq 0 ]; then
 echo "usage: ./plot-fixed (curve25519) (base_cycles|cycles) (jazz|hacl|openssl|boringssl)"
 exit
fi

operation="$1"
type="$2"
filter="$3"

id=${3//[(|)]/_} # removes (, | and ) from the filter
csv=data/$1_$2_$id.csv
gnu=data/$1_$2_$id.gnu
svg=data/$1_$2_$id.svg

idx=0

echo -n "" > $csv

for file in $( ls data/*${operation}*.data | egrep "${filter}" )
do
 filef=${file//data\//}
 filef=${filef//\.data/}
 filef=${filef//crypto_scalarmult_curve25519_/}
 filef=${filef//_/-}
 echo -n "${filef}, " >> $csv
 egrep -o " $type - [0-9]+" "$file" |
 awk '{print $3}' |
 sort | head -n1  >> $csv
done

sort -t, -g -k2 -o $csv $csv

echo "" > $gnu
echo "set term svg enhanced background rgb 'white'" >> $gnu
echo "set title \"curve25519\"" >> $gnu
echo "set output \"$svg\"" >> $gnu
echo "set boxwidth 0.5 relative" >> $gnu
echo "set style fill solid 0.5" >> $gnu
echo "set xlabel \"implementations\"" >> $gnu
echo "set ylabel \"cycles\"" >> $gnu
echo "set xtics rotate" >> $gnu
echo "plot \"$csv\" using 0:2:xticlabels(1) with boxes notitle" >> $gnu

gnuplot $gnu

