#!/bin/bash

# remove previous benchmarks files related to chacha20
ls data/crypto_onetimeauth_poly1305_* | xargs rm

# copy implementations and bindings into supercop-*
./sync
./sync openssl
./sync libsodium
./sync hacl_star

## run benchmarks... this should take some time
./bench poly1305

# move openssl static results to openssl static avx2
mv data/crypto_onetimeauth_poly1305_openssl_static.data data/crypto_onetimeauth_poly1305_openssl_static_avx2.data

# disable avx2 and run openssl benchmarks
(export OPENSSL_ia32cap=~0x200000200000000 && ./bench poly1305-openssl && unset OPENSSL_ia32cap)
mv data/crypto_onetimeauth_poly1305_openssl_static.data data/crypto_onetimeauth_poly1305_openssl_static_avx.data

# plot
./plot poly1305 cycles 16 512
./plot poly1305 cycles 512 4096
./plot poly1305 cycles 4096 16384
