#!/bin/sh -e

version=`cat config/version`

# download and extract supercop
wget https://bench.cr.yp.to/supercop/supercop-$version.tar.xz
unxz < supercop-$version.tar.xz | tar -xf -

# patch okcompilers
cp ./patch/$version/okcompilers/* supercop-$version/okcompilers/

# remove some 'used' files -- do-part used faster
cat ./patch/$version/remove | while read f; do \
  rm -f supercop-$version/$f; \
done

# run ./do-part used inside supercop
(cd supercop-$version/ && ./do-part used)

