#!/bin/sh -e

version=`cat config/version`

# remove the comment from the following line if you want to download
#wget https://bench.cr.yp.to/supercop/supercop-$version.tar.xz

unxz < supercop-$version.tar.xz | tar -xf -

cp ./patch/$version/okcompilers/* supercop-$version/okcompilers/

(cd supercop-$version/ && ./do-part used)

cp ./patch/$version/do-part supercop-$version/do-part
cp ./patch/$version/measure-anything.c supercop-$version/measure-anything.c
cp ./patch/$version/crypto_stream/measure.c supercop-$version/crypto_stream/measure.c
cp ./patch/$version/crypto_onetimeauth/measure.c supercop-$version/crypto_onetimeauth/measure.c

echo "bench" > config/work
mkdir -p data/

