TOP := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
GFLAGS ?=
JFLAGS ?=
JASMINC ?= jasminc

%_export.japp: %.jazz
	gpp -I. -I$(TOP) $(GFLAGS) -DEXPORT -o $@ $<

%.japp: %.jazz
	gpp -I. -I$(TOP) $(GFLAGS) -o $@ $<

%.s: %.japp
	$(JASMINC) $(JFLAGS) -o $@ $< || (rm -f $@ && touch fail)

clean:
	@rm -f fail *.japp *.s
