GFLAGS ?=
JFLAGS ?=
JASMINC ?= jasminc

%.japp: %.jazz
	gpp -I../../../ $(GFLAGS) -o $@ $<

%.s: %.japp
	$(JASMINC) $(JFLAGS) -pasm $< > $@ || rm -f $@

clean:
	rm -f *.japp

full-clean: clean
	rm -f *.s
